### ISSUE TITLE
请问你自考完毕了吗？工作好找吗？

### ISSUE THREAD

**Issue by Snail404** [Zhouxuan-C/self-study_examination#3]
我有点迷茫，考的是专科，已经考过一大半了。但是我怕找不到工作，上了招聘网站好多次，不知道怎么办，我这人不眼高手低，怕的是别人看不上我

**Comment by Snail404** [comment]
希望项目主能回答点什么，比如说自己的现状。或者我自考专科毕业完应该接着干我现在的工作（4000+）然后考自考本科还是尝试找工作

**Comment by Snail404** [comment]
扣完五险一金3000多，每次看到这工资都感觉扎心

**Comment by Zhouxuan-C** [comment]
## 我有点迷茫，考的是专科，已经考过一大半了。但是我怕找不到工作，上了招聘网站好多次，不知道怎么办，我这人不眼高手低，怕的是别人看不上我

其实自考没必要报专科，直接上本科。不过需要注意的是：自考本科毕业时，需要有专科学历才行。
如果大家现在没有专科学历，最好的办法是专科报成人大专，本科报自考。如果顺利大概三年左右就能全部完成。成人大专你打听下，大概 2.5年就能拿学历，给钱然后等就行。自考本科就是稳扎稳打，这三年里专攻本科科目，不需要太多关心大专。等完成自考本科，大专的差不多也到手了。
不过，看您专科已经考过一大半了，还是继续坚持自考专科吧，之后考本科时，如果有之前专科里考过的相同科目，选择免考就行。
除了考试的内容，多关注你那个方向的技术栈和招聘信息吧。我也是新兵一个，没法给太多这方面建议。

## 希望项目主能回答点什么，比如说自己的现状。或者我自考专科毕业完应该接着干我现在的工作（4000+）然后考自考本科还是尝试找工作

关于我，我去年十月报名自考的，最想和大家说的就是 **别临时抱佛脚**，计算机专业的自考本科，好多科目还是很硬核的，就比如今年十月，我计划考的四门科目，因为7月才开始看书，导致最后成绩惨目忍睹，整个过程得托一年，哎，算是一个教训了。
你坚持考完专科，然后肯定要继续自考本科，因为没有本科，真的会失去很多选择。自考期间，多学习多实践，持之以恒，注意技术方面的深度和广度。抓紧自考，等自考完本科，就上一大层台阶了。到时候不管是工作还是继续考研，都会比只有大专好很多。或者那时再来提个 Issues，算是鼓励在我们之后报名自考的同学，你想想多棒啊！
关于薪水，如果你也是新兵一个，真的不用太在意，**坚持自考，别放弃** 就行了！
