### ISSUE TITLE
关于实践考核的难度

### ISSUE THREAD

**Issue by jhzsyang** [Zhouxuan-C/self-study_examination#4]
你好！我看网上关于实践的内容很少，想问一下参与实践考核的内容和难度。
达到及格和达到80大概要需要什么样的准备？
因为实践不要求前置背景，作为初学者感觉心里没底。

**Comment by jhzsyang** [comment]
实践考核只有P/F, 操作系统有难度，其他都很简单。

**Comment by imwillhayes** [comment]
@jhzsyang 哥们方便留个联系方式吗？我邮箱**imwillhayes@gmail**
